name: Build Executable

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main  # Trigger the workflow on pushes to the 'main' branch
  #pull_request:
  #  branches:
  #    - main  # Trigger the workflow on pull requests to the 'main' branch

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            artifact-name: dta-transfer-log-windows
          - os: ubuntu-latest
            artifact-name: dta-transfer-log-ubuntu

    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install additional Linux dependencies (only for Ubuntu)
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk
      
      # Step 5: Build the executable
      - name: Build executable with PyInstaller
        run: |
          pyinstaller main.spec

      - name: Verify dist directory
        shell: bash
        run: ls -la dist

      # Step 6: Upload the executable as an artifact
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: dist/
          retention-days: 7