name: Build Executable

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main  # Trigger the workflow on pushes to the 'main' branch
  #pull_request:
  #  branches:
  #    - main  # Trigger the workflow on pull requests to the 'main' branch

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, rhel9]
        include:
          - os: windows-latest
            artifact-name: dta-transfer-log-windows
          - os: ubuntu-latest
            artifact-name: dta-transfer-log-ubuntu
          - os: rhel9
            artifact-name: dta-transfer-log-rhel9

    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        if: matrix.os != 'rhel9'
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.x

      # Step 3: Install dependencies
      - name: Install dependencies
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "rhel9" ]; then
            python3.11 -m pip install --upgrade pip
            python3.11 -m pip install pyinstaller
            python3.11 -m pip install -r requirements.txt
          else
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          fi

      # Step 4a: Install Ubuntu dependencies
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      # Step 4b: Install RHEL dependencies
      - name: Install RHEL dependencies
        if: matrix.os == 'rhel9'
        run: |
          sudo dnf install -y python3.11-tkinter

      # Step 5: Build the executable
      - name: Build executable with PyInstaller
        run: |
          pyinstaller main.spec

      # Step 6: Verify the dist directory
      - name: Verify dist directory
        shell: bash
        run: ls -la dist

      # Step 7: Upload the executable as an artifact
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: dist/
          retention-days: 7